# Generated by Django 6.0.7 on 2026-08-31 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('recruiter_role', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('employment_type', models.CharField(choices=[('full-time', 'Full Time'), ('contract', 'Contract'), ('c2h', 'Contract-to-Hire')], max_length=20)),
                ('compensation_range', models.CharField(choices=[('50-150k', '$50k–$150k/yr'), ('150-200k', '$150k–$200k/yr'), ('200-500k', '$200k–$500k/yr'), ('500k+', '$500k+/yr')], max_length=20)),
                ('contract_length', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('low_comp', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_role', models.CharField(choices=[('owner', 'owner'), ('recruiter', 'recruiter')], max_length=10)),
                ('body', models.TextField()),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
